### PR TITLE
Replace Ninja with User

### PR DESCRIPTION
**Pull request by adhorrig**
Makes the wording less off-putting 

Ref : https://github.com/CoderDojo/community-platform/issues/917#issuecomment-195310043
https://github.com/CoderDojo/community-platform/issues/934#issuecomment-195301232

### CODE REVIEW

**Comment by niccokunzmann** [comment]
@adhorrig what is the process to merge this? If I look aver it and tested it and say OK. Can you merge it? What needs to be done to merge something?

**Comment by adhorrig** [comment]
@niccokunzmann I don't have merge access myself so I will not be able to do any merging. General process for merging is that we confirm that the code change fixes the issue, and then the PR is merged :)

**Comment by Wardormeur** [comment]
@niccokunzmann I just asnwered on gitter, basically we're in a transition phase for the development team, that's why nothing is actually merge/deployed
Sorry, should have told it earlier :|

**Comment by tangentfairy** [comment]
:+1: from me

**Comment by Wardormeur** [comment]
LGTM :+1: 
However, is there a reason to not use variables in the translation (instead of "below user", replace by the targeted {{username}})? Is it to ease the Crowdin translation? 
(ref https://bitbucket.org/manolakis/dustjs-i18n)

**Pull request merged**
