### PR TITLE
Fix frontend word wrap in dojo's sidebar-contact

### PR DESCRIPTION
**Pull request by rstein66**
Improve readability of sidebar contact info on dojo's main page by specifying that lines should break between words (`break-word`), instead of between any 2 chars (`break-all`).

Closes CoderDojo/community-platform/issues/1207

### CODE REVIEW

**Comment by Wardormeur** [comment]
Please don't introduce a package-lock.
We don't have one for a simplicity reason (internal dependency which is trans-repos, yet need to be updated on each repo : hence master is always picked).
Elsewhat, thanks for the PR :+1:

**Comment by rstein66** [comment]
Oops & thanks! I've removed the file

**Comment by Wardormeur** [comment]
We've released our new front-end (including the dojo page), hence this page isn't used anymore. 
We'll have a proper annoucement soon so that we clearly don't have contribution on dead pieces of code.
Apologies for that :/

**Comment by rstein66** [comment]
I understand; thanks for the update!

**Pull request closed without merging**
