### PR TITLE
fix privacy statement link in footer

### PR DESCRIPTION
**Pull request by kennanseno**

### CODE REVIEW

**Comment by kennanseno** [comment]
also noticed it still says Hello Foundation in the privacy statement, want me to change it to CoderDojo Foundation? @tangentfairy

**Comment by tangentfairy** [comment]
Let's clarify with Rosa! @rosalanghammer are we going with Hello World Foundation or CoderDojo Foundation in the privacy statement?

**Comment by kennanseno** [comment]
noticed the charter link in nav is broken too. fixing it now.

**Comment by Giustina** [comment]
@kennanseno Yes it can change to CoderDojo Foundation thanks!

**Comment by kennanseno** [comment]
updated. false alarm on that charter link, gave me an undefined when I clicked it earlier.

**Comment by tangentfairy** [comment]
Let's remove the absolute link in the footer then @kennanseno - that way it will still work locally with testing. If you want to just change your last commit, you can change the file, then do `git add filename` and `git commit --amend --noedit`

**Comment by kennanseno** [comment]
closing this pr as it's more than just a link problem than initially thought.

https://github.com/CoderDojo/community-platform/issues/866

**Pull request closed without merging**
