### PR TITLE
changes in ordering due to upgrade of seneca-postgresql-store

### PR DESCRIPTION
**Pull request by josmas**
This is 1 in 4 pull requests for https://github.com/CoderDojo/community-platform/issues/839

(3 services + 1 platform)

### CODE REVIEW

**Comment by tangentfairy** [comment]
Changing the sort in manage users or manage dojos gives me a bad request on this branch, but is okay on Master. Did an npm install also. Am I missing something?

**Comment by josmas** [comment]
@tangentfairy 
Testing this is a bit tricky, sorry, I should have added instructions.

Before npm install you need to delete the previous version of the store. Don't know of an automated way of doing this; I just go into node_modules and `rm -rf` the modules I don't want; then `npm install` should bring the new one with all new dependencies. Does that make sense? Otherwise the older module might be found first and loaded (guessing here).

**Comment by tangentfairy** [comment]
Got it! Will give that a whirl, thanks!

**Comment by tangentfairy** [comment]
Looks good! :+1:

**Pull request merged**
