### PR TITLE
changed 'cancel' button text in edit event

### PR DESCRIPTION
**Pull request by notwaving**
In the event form, changed 'Cancel' to 'Discard Changes'. 

For issue, see: https://github.com/CoderDojo/community-platform/issues/1108

#codebar24PR2016

### CODE REVIEW

**Comment by DanielBrierton** [comment]
Thanks for the PR @notwaving! Should make things clearer for people going forward. It should be live once this build finishes: https://circleci.com/gh/CoderDojo/cp-zen-platform/806

**Comment by DanielBrierton** [comment]
Aaaaaand it failed :( Not your fault, just an issue with Crowdin CLI. I'll retrigger again shortly and ping back when it's live.

**Comment by notwaving** [comment]
Oh no!

I was at a #24PullRequests event this weekend, and this was one of my first ever, so apologies if I messed it up. Thanks for keeping me in the loop!

**Comment by DanielBrierton** [comment]
Nope, not your fault at all. It happens from time to time, so don't worry! 😄 

Looks like Crowdin is behaving itself this time: https://circleci.com/gh/CoderDojo/cp-zen-platform/807

**Comment by DanielBrierton** [comment]
After one more build attempt, it worked! 🎉  Your change is now live

discard-changes

Thanks again, and congratulations on your first PR!

**Comment by notwaving** [comment]
Thanks for keeping me updated. So glad it worked!

**Pull request merged**
