### PR TITLE
Adds crowdin information to the footer of the website

### PR DESCRIPTION
**Pull request by sudheesh001**
Fixes https://github.com/CoderDojo/community-platform/issues/912

### CODE REVIEW

**Comment by tangentfairy** [comment]
Nicco is right, you'll need to change the i18n key to the way he has it!

**Comment by sudheesh001** [comment]
@tangentfairy I've made the required changes and rebased, I hope this would be good now. Thank you Nicco :smile:

**Comment by niccokunzmann** [comment]
@tangentfairy I tested it and vote for merge.

**Comment by sudheesh001** [comment]
@tangentfairy Can this go for a merge ? :smile:

**Comment by tangentfairy** [comment]
:+1: Looks good thanks @sudheesh001

**Pull request merged**
