### PR TITLE
nav now same style to main website

### PR DESCRIPTION
**Pull request by kennanseno**
https://github.com/CoderDojo/community-platform/issues/508

change links to be the same w/ main site although left charter link the same.

screen shot 2015-11-25 at 8 49 13 p m

### CODE REVIEW

**Comment by kennanseno** [comment]
@tangentfairy should the last link be dojocon2015 or coolestprojects2016? cause it's still dojocon2015 in the coderdojo website.

**Comment by tangentfairy** [comment]
Coolest projects 2016 :)

**Comment by kennanseno** [comment]
@tangentfairy cool. changed now.

**Comment by kennanseno** [comment]
screen shot 2015-11-27 at 4 11 25 p m
screen shot 2015-11-27 at 5 18 07 p m

**Comment by tangentfairy** [comment]
It seems that on desktop, when logged in, the username and "logout" links are now no longer in line with the content below:

screen shot 2016-01-08 at 16 19 03

Don't spend too much time on this, we are looking at reorganising/redesigning the navigation altogether. If you'd prefer to take a different beginner task and close this pull request it might suit you better!

**Comment by kennanseno** [comment]
will do. :)

**Pull request closed without merging**
