### PR TITLE
add maltese slovenian slovak ukrainian french and Argentinian

### PR DESCRIPTION
**Pull request by butlerx**
for [#988](https://github.com/CoderDojo/community-platform/issues/988)

### CODE REVIEW

**Comment by DanielBrierton** [comment]
You also need to update init-master.js to register the new locales there.

**Comment by butlerx** [comment]
done

**Comment by DanielBrierton** [comment]
Need to change the country to the country's native language

**Comment by butlerx** [comment]
done

**Comment by DanielBrierton** [comment]
..... You missed France... 😛

**Comment by DanielBrierton** [comment]
LGTM now

**Pull request merged**
