### PR TITLE
Part of a fix for #882

### PR DESCRIPTION
**Pull request by danburke**
https://github.com/CoderDojo/community-platform/issues/882

Part of series of pull-requests across 
- cp-zen-platform
- cp-dojos-service
- cp-zen-platform

### CODE REVIEW

**Comment by tangentfairy** [comment]
Looks good to me :+1:

**Comment by sandrobonazzola** [comment]
Commit message doesn't explain the purpose of this single patch in the referenced set of fixes. Other than that, the change looks good to me as well.

**Comment by sandrobonazzola** [comment]
Need rebase.

**Comment by Wardormeur** [comment]
Thanks @danburke, @grabartley and @campbs based their PR on yours :+1:

**Pull request closed without merging**
